<?php 

$trad = [
    "home" => "Главная страница",
    "products" => "Наши продукты",
    "blog" => "Блог",
    "about" => "О проекте",
    "admin" => "Админ",
    "add article" => "Добавить статью",
    "add product" => "Добавить продукт",
    "add" => "Добавить",
    "price" => "Цена",
    "description" => "Описание",
    "edit articles" => "Править статьи",
    "our blog" => "Наш блог",
    "title" => "Заголовок",
    "action" => "Действие",
    "edit" => "Править",
    "delete" => "Удалить",
    "article" => "Статья", 
    "subscribe" => "Подписаться",
    "subscribe to the newsletter" => "Подпишитесь на нашу рассылку!",
    "contact" => "Контакты",
    "navigation" => "Навигация",
    "social media" => "Наши соцсети",
    "your email" => "Ваша почта:", 
    "password" => "Введите пароль:",
    "editing" => "Правка",
    "author" => "Автор",
    "text" => "Текст",
    "publish" => "Опубликовать",
    "buy" => "Купить",
    "heading" => "Заголовок",
    "register" => "Зарегистрироваться"
];